### ISSUE TITLE
Holiday/ROL entry

### ISSUE THREAD

**Issue by MaurizioSodano** [soulsoftware/Powerapps-Timesheet#1]
When inserting a new Entry, Remove Project selection when the Reason is Holiday, ROL, Sick Leave,...

**Comment by bsorrentino** [comment]
Hi @MaurizioSodano thanks for feedback.

I'll investigate how to implement such exception

**Comment by bsorrentino** [comment]
Hi All

from version `2.4.1` of `Soul Timesheet App` has been introduced a special project `_Nothing_` that could be used in case of **non billable hours` that are:

* Absence, 
* Holiday, 
* Hours off
* ROL 
* Sick leave
